### Exercise

 **A.** Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

In [1]:
import numpy as np

# * import numpy loads the numpy library so we can use it
# * as np gives it a shorter nickname np so we don't have to type numpy every time

In [2]:
# Creating a nested Python list with values chosen from 1-100
# This makes a 4x5 array (4 rows, 5 columns)
A = np.array([
    [10, 25, 33, 47, 58],
    [62, 71, 85, 90, 14],
    [39, 52, 67, 78, 83],
    [91, 44, 16, 29, 55]
])

# * A = stores the array in a variable named A
# * np.array() converts the nested list into a numpy array
# * Each [ ] inside represents one row of the array
# * 4 inner lists = 4 rows, 5 numbers each = 5 columns
# * displays the array on screen

print(A)

# displays the array on screen

[[10 25 33 47 58]
 [62 71 85 90 14]
 [39 52 67 78 83]
 [91 44 16 29 55]]


1. Using a property of the ndarray object
      - e.g. `A.shape`

In [3]:
# 1. Using a PROPERTY of the ndarray object

print(A.shape)  # returns (4, 5) → 4 rows and 5 columns

#.shape tells you the size of each dimension
# Output: (4, 5) 4 rows, 5 columns

print(A.ndim)   # returns 2 → it is a 2D array

# .ndim tells you how many dimensions the array has
# Output: 2 it has rows AND columns so it's 2D

print(A.size)   # returns 20 → total elements (4x5)

# .size tells you the total number of elements
# Output: 20 because 4 × 5 = 20

print(A.dtype)  # returns int64 → values are integers

# .dtype tells you the data type of the values
# Output: int64 all values are integers


(4, 5)
2
20
int64


2. Using a method of the ndarray object
      - e.g. `A.max()`

In [4]:
# 2. Using a METHOD of the ndarray object

print(A.max())  # returns the highest value → 91

# .max() finds and returns the highest value in the array
# Output: 91 the biggest number in array A

print(A.min())  # returns the lowest value → 10

# .min() finds and returns the lowest value in the array
# Output: 10 the smallest number in array A

print(A.sum())  # returns the total sum of all elements

# .sum() adds all elements together and returns the total
# Output: sum of all 20 numbers in the array

print(A.mean())  # returns the average of all elements

# .mean() calculates the average of all elements
# Output: total sum divided by number of elements

91
10
1049
52.45


3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

In [5]:
# 3. Using a NUMPY FUNCTION passing an ndarray

print(np.max(A))  # returns the highest value → 91

# np.max(A) same result as A.max() but uses numpy's built-in function
# Output: 91 the biggest number in array A

print(np.min(A))  # returns the lowest value → 10

# np.min(A) same as A.min() but called as a numpy function
# Output: 10 the smallest number in array A

print(np.sum(A))  # returns the total sum of all elements

# np.sum(A) same as A.sum() but called as a numpy function
# Output: total sum of all 20 numbers in the array

print(np.mean(A))  # returns the average of all elements

# np.mean(A) same as A.mean() but called as a numpy function
# Output: total sum divided by number of elements

91
10
1049
52.45


**B.** Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

In [13]:
B = np.ones((5, 5), dtype=int)  # creates a 5x5 array filled with 1s

# np.ones() creates an array filled with 1s
# (5, 5) means 5 rows and 5 columns
# dtype=int makes sure values are integers not decimals

print(B)

# displays the 5x5 array of ones on screen

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [14]:
print(B.shape)  # returns (5, 5) → 5 rows and 5 columns

# .shape returns the dimensions of the array
# Output: (5, 5) 5 rows and 5 columns

(5, 5)


In [15]:
print(B.size)  # returns 25 → total number of elements

# .size returns total number of elements
# Output: 25 because 5 × 5 = 25

25


In [9]:
print(B.ndim)

# .ndim → returns the number of dimensions
# Output: 2 → it is a 2D array (has both rows and columns)

2


**C.** Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [10]:
C = np.arange(-5, 6)  # creates a sequence of numbers from -5 to +5

# np.arange() creates a sequence like range() but returns a numpy array
# -5 is the starting value (included)
# 6 is the stopping value (not included) so last number is 5

print(C)

# displays the original array

[-5 -4 -3 -2 -1  0  1  2  3  4  5]


In [17]:
C_multiplied = C * 2

# C * 2 → takes every number in array C and multiplies it by 2
# numpy does this all at once without needing a loop
# C_multiplied = → stores the new multiplied values into a new variable

print(C_multiplied)
# display Output: [-10  -8  -6  -4  -2   0   2   4   6   8  10]

In [18]:

print("Original array:")  # prints a label for readability
print(C)                  # prints the original array

print("After multiplying by 2:")  # prints another label
print(C_multiplied)               # prints the final result

# display Output: [-10  -8  -6  -4  -2   0   2   4   6   8  10]

Original array:
[-5 -4 -3 -2 -1  0  1  2  3  4  5]
After multiplying by 2:
[-10  -8  -6  -4  -2   0   2   4   6   8  10]
